version: "3.3"
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - $PWD:/opt/app
    environment:
      - RUNTYPE=bash
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/opt/app
    environment:
      - RUNTYPE=celery_worker
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    depends_on:
      - redis
      - db

  beater:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/opt/app
    environment:
      - RUNTYPE=celery_beater
      - PYTHONDONTWRITEBYTECODE=1
    env_file:
      - .env
    depends_on:
      - db
      - worker
      - redis

volumes:
  app:
  app-db-data:
