version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  test:
    docker:
      - image: cimg/python:3.10
        environment:
          POSTGRES_DB: "test"
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "test"
          POSTGRES_SERVER: "localhost"
          POSTGRES_PORT: 5432
          SENTRY_DSN: http://YourSentryDSN.com
          FIRST_SUPERUSER: admin@yourproject.com
          FIRST_SUPERUSER_PASSWORD: admin
          CELERY_BROKER_URL: redis://redis:6379/0
          CELERY_RESULT_BACKEND: redis://redis:6379/0

      - image: cimg/postgres:13.7
        environment:
          POSTGRES_DB: "test"
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "test"

    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            mkdir test-results
            poetry run pytest . -p no:warnings --junitxml=test-results/junit.xml
          name: Run tests

      - store_test_results:
          path: test-results

  lint:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Run pre commit install
          command: poetry run pre-commit install

      - run:
          name: Run pre commit check
          command: poetry run pre-commit run -a

workflows:
  common:
    jobs:
      - lint
      - test
